/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.awt.*;

/**
 *
 * @author malu_
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        mainPanel = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        entrarbt = new javax.swing.JButton();
        senhatxt = new javax.swing.JPasswordField();
        logintxt = new javax.swing.JTextField();
        Loginlabel = new javax.swing.JLabel();
        Senhalabel = new javax.swing.JLabel();
        bemvindolabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pinicialo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        contaobt = new javax.swing.JButton();
        homeobt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Orientadoslabel = new javax.swing.JLabel();
        aoobt = new javax.swing.JButton();
        pioobt = new javax.swing.JButton();
        toobt = new javax.swing.JButton();
        mobt = new javax.swing.JButton();
        piniciala = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        contaabt = new javax.swing.JButton();
        homeabt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ccabt = new javax.swing.JButton();
        arabt = new javax.swing.JButton();
        mtabt = new javax.swing.JButton();
        alunosorientados = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        barra4 = new javax.swing.JPanel();
        contaobt1 = new javax.swing.JButton();
        homeobt1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        pesquisartf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oriesptabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        origratabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));

        entrarbt.setText("Entrar");
        entrarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarbtActionPerformed(evt);
            }
        });

        senhatxt.setText("senha");

        logintxt.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        logintxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        logintxt.setText("usuário");

        Loginlabel.setText("Login");

        Senhalabel.setText("Senha");

        bemvindolabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bemvindolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bemvindolabel.setText("Bem Vindo");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(Senhalabel)
                        .addGap(26, 26, 26)
                        .addComponent(senhatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(entrarbt)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(Loginlabel)
                        .addGap(28, 28, 28)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bemvindolabel)
                            .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(266, 266, 266))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(bemvindolabel)
                .addGap(32, 32, 32)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Loginlabel)
                    .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senhalabel)
                    .addComponent(senhatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(entrarbt)
                .addGap(139, 139, 139))
        );

        mainPanel.add(Login, "Login");

        pinicialo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        contaobt.setBackground(new java.awt.Color(0, 102, 204));
        contaobt.setForeground(new java.awt.Color(255, 255, 255));
        contaobt.setText("Conta");

        homeobt.setBackground(new java.awt.Color(0, 102, 204));
        homeobt.setForeground(new java.awt.Color(255, 255, 255));
        homeobt.setText("Home");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeobt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contaobt)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaobt)
                    .addComponent(homeobt))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setText("Ola, XXX");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Docente Orientador:");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        Orientadoslabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Orientadoslabel.setText("Orientados:");

        aoobt.setBackground(new java.awt.Color(102, 204, 255));
        aoobt.setForeground(new java.awt.Color(255, 255, 255));
        aoobt.setText("Alunos Orientados");
        aoobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoobtActionPerformed(evt);
            }
        });

        pioobt.setBackground(new java.awt.Color(102, 204, 255));
        pioobt.setForeground(new java.awt.Color(255, 255, 255));
        pioobt.setText("Professores ISF Orientados");

        toobt.setBackground(new java.awt.Color(102, 204, 255));
        toobt.setForeground(new java.awt.Color(255, 255, 255));
        toobt.setText("Todos Orientadores");

        mobt.setBackground(new java.awt.Color(102, 204, 255));
        mobt.setForeground(new java.awt.Color(255, 255, 255));
        mobt.setText("Materiais");

        javax.swing.GroupLayout pinicialoLayout = new javax.swing.GroupLayout(pinicialo);
        pinicialo.setLayout(pinicialoLayout);
        pinicialoLayout.setHorizontalGroup(
            pinicialoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pinicialoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinicialoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pinicialoLayout.createSequentialGroup()
                        .addGroup(pinicialoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(pinicialoLayout.createSequentialGroup()
                                .addGroup(pinicialoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(Orientadoslabel)
                                    .addGroup(pinicialoLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pinicialoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pinicialoLayout.createSequentialGroup()
                        .addComponent(aoobt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(pioobt)
                        .addGap(58, 58, 58)
                        .addComponent(toobt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(pinicialoLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(mobt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pinicialoLayout.setVerticalGroup(
            pinicialoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinicialoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Orientadoslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pinicialoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aoobt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pioobt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toobt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(mobt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
        );

        mainPanel.add(pinicialo, "pinicialo");

        piniciala.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        contaabt.setBackground(new java.awt.Color(0, 102, 204));
        contaabt.setForeground(new java.awt.Color(255, 255, 255));
        contaabt.setText("conta");

        homeabt.setBackground(new java.awt.Color(0, 102, 204));
        homeabt.setForeground(new java.awt.Color(255, 255, 255));
        homeabt.setText("Home");
        homeabt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeabtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(homeabt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contaabt)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaabt)
                    .addComponent(homeabt))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel1.setText("Ola, xxx");

        ccabt.setBackground(new java.awt.Color(102, 204, 255));
        ccabt.setForeground(new java.awt.Color(255, 255, 255));
        ccabt.setText("Componente Curricular");

        arabt.setBackground(new java.awt.Color(102, 204, 255));
        arabt.setForeground(new java.awt.Color(255, 255, 255));
        arabt.setText("Adicionar ao Repositório");

        mtabt.setBackground(new java.awt.Color(102, 204, 255));
        mtabt.setForeground(new java.awt.Color(255, 255, 255));
        mtabt.setText("Matricular em Turma");

        javax.swing.GroupLayout pinicialaLayout = new javax.swing.GroupLayout(piniciala);
        piniciala.setLayout(pinicialaLayout);
        pinicialaLayout.setHorizontalGroup(
            pinicialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pinicialaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinicialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pinicialaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ccabt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arabt)
                        .addGap(18, 18, 18)
                        .addComponent(mtabt)
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addGroup(pinicialaLayout.createSequentialGroup()
                        .addGroup(pinicialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(pinicialaLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pinicialaLayout.setVerticalGroup(
            pinicialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinicialaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinicialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arabt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pinicialaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccabt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mtabt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(252, 252, 252))
        );

        mainPanel.add(piniciala, "piniciala");

        alunosorientados.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Ola, XXX");

        barra4.setBackground(new java.awt.Color(102, 204, 255));

        contaobt1.setBackground(new java.awt.Color(0, 102, 204));
        contaobt1.setForeground(new java.awt.Color(255, 255, 255));
        contaobt1.setText("Conta");

        homeobt1.setBackground(new java.awt.Color(0, 102, 204));
        homeobt1.setForeground(new java.awt.Color(255, 255, 255));
        homeobt1.setText("Home");
        homeobt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeobt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barra4Layout = new javax.swing.GroupLayout(barra4);
        barra4.setLayout(barra4Layout);
        barra4Layout.setHorizontalGroup(
            barra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barra4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeobt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                .addComponent(contaobt1)
                .addGap(18, 18, 18))
        );
        barra4Layout.setVerticalGroup(
            barra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaobt1)
                    .addComponent(homeobt1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pesquisartf.setBackground(new java.awt.Color(153, 204, 255));
        pesquisartf.setForeground(new java.awt.Color(255, 255, 255));
        pesquisartf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pesquisartf.setText("  Pesquisar");

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nova Orientação Especialização");

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Nova Orientação Graduando");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Especialização");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Graduando");

        oriesptabela.setBackground(new java.awt.Color(153, 204, 255));
        oriesptabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Orientado", "Nome", "Número", "E-mail", "Ação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(oriesptabela);

        origratabela.setBackground(new java.awt.Color(153, 204, 255));
        origratabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Orientado", "Nome", "Número", "E-mail", "Ação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(origratabela);

        javax.swing.GroupLayout alunosorientadosLayout = new javax.swing.GroupLayout(alunosorientados);
        alunosorientados.setLayout(alunosorientadosLayout);
        alunosorientadosLayout.setHorizontalGroup(
            alunosorientadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(alunosorientadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alunosorientadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alunosorientadosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(alunosorientadosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(alunosorientadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alunosorientadosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(alunosorientadosLayout.createSequentialGroup()
                        .addComponent(pesquisartf, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(alunosorientadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(alunosorientadosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(alunosorientadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(alunosorientadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        alunosorientadosLayout.setVerticalGroup(
            alunosorientadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunosorientadosLayout.createSequentialGroup()
                .addComponent(barra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunosorientadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisartf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainPanel.add(alunosorientados, "alunosorientados");

        getContentPane().add(mainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarbtActionPerformed
        // TODO add your handling code here:
        if(logintxt.getText().equals("aluno")){
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "piniciala");
        }
        else{
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "pinicialo");
        }
        
        
    }//GEN-LAST:event_entrarbtActionPerformed

    private void homeabtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeabtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeabtActionPerformed

    private void aoobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoobtActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "alunosorientados");
    }//GEN-LAST:event_aoobtActionPerformed

    private void homeobt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeobt1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "pinicialo");
    }//GEN-LAST:event_homeobt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Loginlabel;
    private javax.swing.JLabel Orientadoslabel;
    private javax.swing.JLabel Senhalabel;
    private javax.swing.JPanel alunosorientados;
    private javax.swing.JButton aoobt;
    private javax.swing.JButton arabt;
    private javax.swing.JPanel barra4;
    private javax.swing.JLabel bemvindolabel;
    private javax.swing.JButton ccabt;
    private javax.swing.JButton contaabt;
    private javax.swing.JButton contaobt;
    private javax.swing.JButton contaobt1;
    private javax.swing.JButton entrarbt;
    private javax.swing.JButton homeabt;
    private javax.swing.JButton homeobt;
    private javax.swing.JButton homeobt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField logintxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mobt;
    private javax.swing.JButton mtabt;
    private javax.swing.JTable oriesptabela;
    private javax.swing.JTable origratabela;
    private javax.swing.JTextField pesquisartf;
    private javax.swing.JPanel piniciala;
    private javax.swing.JPanel pinicialo;
    private javax.swing.JButton pioobt;
    private javax.swing.JPasswordField senhatxt;
    private javax.swing.JButton toobt;
    // End of variables declaration//GEN-END:variables
}
